apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-cni
  namespace: kube-system
data:
  plugins: multus-cni,macvlan,ipvlan
  configs: 05-multus-cni.conf
  manifests: multus-cni-crd.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-cni-configs
  namespace: kube-system
data:
  05-multus-cni.conf: |
    {"name": "multus-cni",
     "cniVersion":"0.1.0",
     "type": "multus-cni",
     "kubeconfig": "/etc/kubernetes/kubelet.conf",
     "delegates": [
       __10-calico.conflist__
     ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: multus-cni-manifests
  namespace: kube-system
data:
  multus-cni-crd.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: multus-cni-${NODE_HOSTNAME}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: multus-cni-crd
    subjects:
    - kind: User
      name: system:node:${NODE_HOSTNAME}
      apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: multus-cni
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: multus-cni
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["k8s.cni.cncf.io"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods", "pods/status"]
  verbs: ["get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: multus-cni
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: multus-cni
subjects:
- kind: ServiceAccount
  name: multus-cni
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: multus-cni
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["multus-cni"]
  verbs: ["get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: multus-cni
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multus-cni
subjects:
- kind: ServiceAccount
  name: multus-cni
