apiVersion: kubeadm.k8s.io/v1alpha3
kind: ClusterConfiguration
kubernetesVersion: _K8S_VERSION_
apiServerCertSANs:
- "_API_HOSTNAME_"
controlPlaneEndpoint: "kubernetes:6443"
etcd:
  local:
    extraArgs:
      listen-client-urls: "https://127.0.0.1:2379,https://_NODE_IP_:2379"
      advertise-client-urls: "https://_NODE_IP_:2379"
      listen-peer-urls: "https://_NODE_IP_:2380"
      initial-advertise-peer-urls: "https://_NODE_IP_:2380"
      initial-cluster: "_ETCD_CLUSTER__NODE_HOSTNAME_=https://_NODE_IP_:2380"
      initial-cluster-state: "_ETCD_STATE_"
    serverCertSANs:
    - "_NODE_HOSTNAME_"
    - "_NODE_IP_"
    peerCertSANs:
    - "_NODE_HOSTNAME_"
    - "_NODE_IP_"
networking:
    podSubnet: "10.233.64.0/18"
    serviceSubnet: "10.233.0.0/18"
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1alpha3
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:
- "10.233.0.10"
